name: "Code Scanning - Action"

on:
  push:
  # schedule:
    #        ┌───────────── minute (0 - 59)
    #        │  ┌───────────── hour (0 - 23)
    #        │  │ ┌───────────── day of the month (1 - 31)
    #        │  │ │ ┌───────────── month (1 - 12 or JAN-DEC)
    #        │  │ │ │ ┌───────────── day of the week (0 - 6 or SUN-SAT)
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        │  │ │ │ │
    #        *  * * * *
    # - cron: '30 1 * * 0'

jobs:
  CodeQL-Build:
    # CodeQL runs on ubuntu-latest, windows-latest, and macos-latest
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Initializes the CodeQL tools for scanning.
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v1
        # Override language selection by uncommenting this and choosing your languages
        with:
          languages: python

      # Autobuild attempts to build any compiled languages (C/C++, C#, or Java).
      # If this step fails, then you should remove it and run the build manually (see below).
      - name: Autobuild
        uses: github/codeql-action/autobuild@v1

      # ℹ️ Command-line programs to run using the OS shell.
      # 📚 https://git.io/JvXDl

      # ✏️ If the Autobuild fails above, remove it and uncomment the following
      #    three lines and modify them (or add more) to build your code if your
      #    project uses a compiled language

      #- run: |
      #   make bootstrap
      #   make release
      - name: Wait for python app build success
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-build-success
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: Python App
          ref: ${{ github.event.pull_request.head.sha || github.sha }}

      - name: Perform CodeQL Analysis
        if: steps.wait-for-build-success.outputs.conclusion == 'success'
        uses: github/codeql-action/analyze@v1
      
      - name: Error message on failure
        if: steps.wait-for-build-success.outputs.conclusion == 'failure'
        run: echo "ERROR! Cannot scan code base for security issues with a build failure!
