# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python Functional Tests

on:
  push:
    branches-ignore: main

jobs:
  functional-tests:
    name: Functional Tests
    runs-on: ubuntu-latest
    container: python:3.6.12-alpine3.12
    
    steps:
    # Checkout the source code
    - name: Checkout source code
      uses: actions/checkout@v2
      
    # install the dependencies
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest pipenv
        # if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pipenv install

    # Run the pytests     
    - name: Functional Test with pytest
      run: |
        pytest .
  
